<?php

namespace Database\Seeders;

use App\Models\CAP;
use App\Models\RiskAssessment;
use App\Models\SAQ;
use App\Models\SalesProduct;
use App\Models\Supplier;
use App\Models\TradeGoodPathRisk;
use App\Services\Compliance\MarketComplianceChecker;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

/**
 * Dual-Risk Dashboard DEMO 資料
 *
 * 1. 對所有 SalesProduct × 市場 執行 MarketComplianceChecker，
 *    計算合規義務缺口並寫入 trade_good_path_risks。
 * 2. 對有 RiskAssessment 的供應商填入三軸評分。
 */
class DualRiskDashboardDemoSeeder extends Seeder
{
    private const MARKETS = ['EU', 'US', 'APAC', 'GB', 'JP'];

    // 三軸 DEMO（supplier code => [axis1, axis2, axis3]）
    private const AXIS_SCENARIOS = [
        'SUP-VGE-001' => [72.0, 65.0, 45.0],
        'SUP-TPS-001' => [38.0, 42.0, 60.0],
        'SUP-DGF-001' => [55.0, 38.0, 75.0],
        'SUP-BGN-001' => [25.0, 28.0, 82.0],
        'JPS-001'     => [80.0, 78.0, 20.0],
    ];

    // 靜態 fallback：當商品無合規規則時補充 DEMO 分數
    // 按商品 HS code prefix 對應風險場景
    private const STATIC_SCENARIOS = [
        // HS 61xx 成衣：UFLPA 高壓美國市場
        '61' => ['EU' => [0.9,'medium'], 'US' => [1.95,'extreme'], 'APAC' => [0.3,'low'], 'GB' => [0.85,'medium'], 'JP' => [0.2,'very_low']],
        // HS 59xx / 60xx 布料：EUDR 歐盟木漿溯源
        '59' => ['EU' => [1.65,'extreme'], 'US' => [0.42,'low'], 'APAC' => [0.38,'low'], 'GB' => [1.52,'high'], 'JP' => [0.25,'very_low']],
        '60' => ['EU' => [1.65,'extreme'], 'US' => [0.42,'low'], 'APAC' => [0.38,'low'], 'GB' => [1.52,'high'], 'JP' => [0.25,'very_low']],
        // HS 52xx / 55xx 紗線：UFLPA 棉花溯源
        '52' => ['EU' => [0.78,'medium'], 'US' => [1.35,'high'], 'APAC' => [0.22,'very_low'], 'GB' => [0.68,'medium'], 'JP' => [0.31,'low']],
        '55' => ['EU' => [0.78,'medium'], 'US' => [1.35,'high'], 'APAC' => [0.22,'very_low'], 'GB' => [0.68,'medium'], 'JP' => [0.31,'low']],
        // 預設（其他 HS code）
        'default' => ['EU' => [0.5,'low'], 'US' => [0.4,'low'], 'APAC' => [0.15,'very_low'], 'GB' => [0.45,'low'], 'JP' => [0.2,'very_low']],
    ];

    // Demo auto-generated CAP scenarios（軸分 >= 80 → extreme）
    private const CAP_DEMO = [
        'JPS-001' => [
            'axis1' => [
                'score' => 80.0,
                'title' => '[ISO 26000] 供應商 ESG 揭露風險嚴重超標（分數：80.0）',
                'findings' => [
                    ['slug' => 'iso26k.env.climate',    'label' => '氣候變遷因應',     'score' => 32.0],
                    ['slug' => 'iso26k.env.pollution',  'label' => '汙染預防',          'score' => 41.5],
                    ['slug' => 'iso26k.labor.safe',     'label' => '職業安全衛生',      'score' => 45.0],
                ],
            ],
        ],
    ];

    public function run(): void
    {
        $this->seedPathRisks();
        $this->seedAxisScores();
        $this->seedAutoGeneratedCaps();
    }

    private function seedPathRisks(): void
    {
        /** @var MarketComplianceChecker $checker */
        $checker  = app(MarketComplianceChecker::class);
        $products = SalesProduct::with([
            'tradeGoodSuppliers.materialGroup',
            'tradeGoodSuppliers.supplier',
        ])->get();

        $expires  = now()->addHours(24);
        $inserted = 0;

        foreach ($products as $product) {
            foreach (self::MARKETS as $market) {
                try {
                    $compliance = $checker->check($product, $market);
                    $result     = $this->calcRisk($compliance, $product, $market);
                } catch (\Throwable) {
                    $result = $this->staticFallback($product, $market);
                }

                TradeGoodPathRisk::updateOrCreate(
                    ['trade_good_id' => $product->id, 'market' => $market],
                    [
                        'id'              => Str::uuid(),
                        'path_risk_score' => $result['path_risk_score'],
                        'risk_level'      => $result['risk_level'],
                        'amplifier'       => $result['amplifier'],
                        'chain_risk'      => $result['obligation_score'],
                        'has_data_gap'    => $result['has_data_gap'],
                        'contributors'    => $result['obligations'],
                        'calculated_at'   => now(),
                        'expires_at'      => $expires,
                    ]
                );
                $inserted++;
            }
        }

        $this->command->info("✓ 已建立 {$inserted} 筆合規義務路徑風險 DEMO 資料（{$products->count()} 商品 × " . count(self::MARKETS) . " 市場）");
    }

    private function calcRisk(array $compliance, SalesProduct $product, string $market): array
    {
        $results  = $compliance['results'] ?? [];
        $required = $compliance['required'] ?? [];

        // 無適用義務 → 使用靜態 fallback
        if (empty($required)) {
            return $this->staticFallback($product, $market);
        }

        $totalRequired   = count($required);
        $missingCount    = 0;
        $obligationScore = 0.0;
        $obligations     = [];

        foreach ($results as $ob) {
            $weight = ($ob['is_mandatory'] ?? true) ? 1.0 : 0.5;
            $status = $ob['status'];

            $contribution = match ($status) {
                'missing', 'expired' => 1.0 * $weight,
                'expiring_soon'      => 0.5 * $weight,
                default              => 0.0,
            };

            if (in_array($status, ['missing', 'expired'])) {
                $missingCount++;
            }

            $obligationScore += $contribution;
            $obligations[] = [
                'doc_type'     => $ob['doc_type'],
                'status'       => $status,
                'is_mandatory' => $ob['is_mandatory'] ?? true,
                'contribution' => round($contribution, 3),
                'expires_at'   => $ob['expires_at'] ?? null,
            ];
        }

        $coverageGap   = $totalRequired > 0 ? $missingCount / $totalRequired : 0;
        $amplifier     = round(1 + $coverageGap, 3);
        $pathRiskScore = round($obligationScore * $amplifier, 3);

        return [
            'path_risk_score' => $pathRiskScore,
            'risk_level'      => $this->scoreToLevel($pathRiskScore),
            'amplifier'       => $amplifier,
            'obligation_score' => round($obligationScore, 3),
            'has_data_gap'    => $missingCount > 0,
            'obligations'     => $obligations,
        ];
    }

    private function staticFallback(SalesProduct $product, string $market): array
    {
        $prefix   = substr($product->hs_code ?? '', 0, 2);
        $scenario = self::STATIC_SCENARIOS[$prefix] ?? self::STATIC_SCENARIOS['default'];
        [$score, $level] = $scenario[$market];

        // 加一點隨機性讓 demo 更自然
        $score = round($score + (rand(-15, 15) / 100), 2);
        $score = max(0.0, $score);
        $level = $this->scoreToLevel($score);

        return [
            'path_risk_score' => $score,
            'risk_level'      => $level,
            'amplifier'       => 1.0,
            'obligation_score' => $score,
            'has_data_gap'    => false,
            'obligations'     => [],
        ];
    }

    private function scoreToLevel(float $score): string
    {
        return match (true) {
            $score >= 1.6 => 'extreme',
            $score >= 1.2 => 'high',
            $score >= 0.8 => 'medium',
            $score >= 0.4 => 'low',
            default       => 'very_low',
        };
    }

    private function seedAxisScores(): void
    {
        $suppliers = Supplier::all()->keyBy('code');
        $updated   = 0;

        foreach (self::AXIS_SCENARIOS as $code => [$a1, $a2, $a3]) {
            $supplier = $suppliers->get($code);
            if (!$supplier) continue;

            $latest = RiskAssessment::where('supplier_id', $supplier->id)
                ->orderBy('assessed_at', 'desc')
                ->first();

            if ($latest) {
                $latest->update(['axis1_score' => $a1, 'axis2_score' => $a2, 'axis3_score' => $a3]);
            } else {
                RiskAssessment::create([
                    'id'          => Str::uuid(),
                    'supplier_id' => $supplier->id,
                    'axis1_score' => $a1,
                    'axis2_score' => $a2,
                    'axis3_score' => $a3,
                    'assessed_at' => now(),
                    'assessed_by' => 'demo_seed',
                ]);
            }
            $updated++;
        }

        // Fallback：對所有還沒有三軸評分的 RiskAssessment 補值
        $noAxis = RiskAssessment::whereNull('axis1_score')->limit(20)->get();
        foreach ($noAxis as $ra) {
            $ra->update([
                'axis1_score' => rand(25, 85),
                'axis2_score' => rand(20, 80),
                'axis3_score' => rand(15, 75),
            ]);
            $updated++;
        }

        // 對還沒有 RiskAssessment 的供應商建立一筆（直接寫 DB 繞過 NOT NULL 舊欄位）
        Supplier::limit(10)->get()->each(function (Supplier $s) use (&$updated) {
            if (!RiskAssessment::where('supplier_id', $s->id)->exists()) {
                \DB::table('risk_assessments')->insert([
                    'id'            => Str::uuid(),
                    'supplier_id'   => $s->id,
                    'axis1_score'   => rand(25, 85),
                    'axis2_score'   => rand(20, 80),
                    'axis3_score'   => rand(15, 75),
                    'e_probability' => 0,
                    'e_impact'      => 0,
                    's_probability' => 0,
                    's_impact'      => 0,
                    'g_probability' => 0,
                    'g_impact'      => 0,
                    'gp_probability'=> 0,
                    'gp_impact'     => 0,
                    'assessed_at'   => now(),
                    'assessed_by'   => 'demo_seed',
                    'created_at'    => now(),
                    'updated_at'    => now(),
                ]);
                $updated++;
            }
        });

        $this->command->info("✓ 已更新 {$updated} 筆供應商三軸評分 DEMO 資料");
    }

    private function seedAutoGeneratedCaps(): void
    {
        $suppliers = Supplier::all()->keyBy('code');
        $created   = 0;

        foreach (self::CAP_DEMO as $code => $axes) {
            $supplier = $suppliers->get($code);
            if (!$supplier) continue;

            $ra  = RiskAssessment::where('supplier_id', $supplier->id)->orderByDesc('assessed_at')->first();
            $saq = SAQ::where('supplier_id', $supplier->id)->orderByDesc('created_at')->first();

            foreach ($axes as $axis => $cfg) {
                // 冪等保護
                $exists = CAP::where('supplier_id', $supplier->id)
                    ->where('triggered_by_axis', $axis)
                    ->where('auto_generated', true)
                    ->whereNotIn('status', ['closed'])
                    ->exists();
                if ($exists) continue;

                $cap = CAP::create([
                    'id'                => Str::uuid(),
                    'supplier_id'       => $supplier->id,
                    'saq_id'            => $saq?->id,
                    'source_type'       => 'risk_assessment',
                    'source_id'         => $ra?->id,
                    'triggered_by_axis' => $axis,
                    'auto_generated'    => true,
                    'title'             => $cfg['title'],
                    'priority'          => 'critical',
                    'status'            => 'open',
                    'due_date'          => now()->addDays(30)->toDateString(),
                    'created_by'        => null,
                ]);

                foreach ($cfg['findings'] as $f) {
                    $cap->findings()->create([
                        'framework'    => 'iso26k',
                        'topic_slug'   => $f['slug'],
                        'source_score' => $f['score'],
                        'threshold'    => 60.0,
                        'finding'      => sprintf('%s 評分 %s/100，低於及格線 60', $f['label'], $f['score']),
                        'status'       => 'open',
                    ]);
                }
                $created++;
            }
        }

        $this->command->info("✓ 已建立 {$created} 筆自動生成 CAP DEMO 資料");
    }
}
