<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

/**
 * 題目庫種子資料：四大領域各 10 題，template_id = NULL 表示題庫題目
 */
class QuestionBankSeeder extends Seeder
{
    public function run(): void
    {
        $questions = $this->questions();

        foreach ($questions as $q) {
            $slugs = $q['tag_slugs'];
            unset($q['tag_slugs']);

            $existing = DB::table('saq_questions')
                ->whereNull('template_id')
                ->where('question_text', $q['question_text'])
                ->first();

            if ($existing) {
                $questionId = $existing->id;
            } else {
                $questionId = Str::uuid()->toString();
                DB::table('saq_questions')->insert(array_merge($q, [
                    'id'         => $questionId,
                    'created_at' => now(),
                    'updated_at' => now(),
                ]));
            }

            // 寫入 tag assignments
            foreach ($slugs as $slug) {
                $tag = DB::table('question_tags')->where('slug', $slug)->first();
                if (!$tag) continue;
                DB::table('question_tag_assignments')
                    ->insertOrIgnore([
                        'question_id' => $questionId,
                        'tag_id'      => $tag->id,
                    ]);
            }
        }
    }

    private function questions(): array
    {
        return [
            // ────────────────────────────────────────────────────────────
            // ESG 領域（10 題）
            // ────────────────────────────────────────────────────────────
            [
                'template_id'   => null,
                'question_text' => '貴公司是否已建立溫室氣體盤查制度，並依據 ISO 14064 或 GHG Protocol 進行 Scope 1/2/3 排放量計算？',
                'question_type' => 'single_choice',
                'options'       => json_encode(['完全符合', '大部分符合', '部分符合', '少部分符合', '不符合']),
                'weight'        => 0.15,
                'order'         => 1,
                'is_required'   => true,
                'sasb_topic_id' => null,
                'sasb_metric_code' => null,
                'tags'          => null,
                'source_bank_question_id' => null,
                'tag_slugs'     => ['esg.e.ghg'],
            ],
            [
                'template_id'   => null,
                'question_text' => '貴公司是否設定溫室氣體減排目標（如 SBTi 科學基礎目標），並有具體的年度減排路徑？',
                'question_type' => 'single_choice',
                'options'       => json_encode(['完全符合', '大部分符合', '部分符合', '少部分符合', '不符合']),
                'weight'        => 0.12,
                'order'         => 2,
                'is_required'   => true,
                'sasb_topic_id' => null,
                'sasb_metric_code' => null,
                'tags'          => null,
                'source_bank_question_id' => null,
                'tag_slugs'     => ['esg.e.ghg'],
            ],
            [
                'template_id'   => null,
                'question_text' => '貴公司是否建立用水量監測與節水目標，並追蹤高水壓地區的用水風險？',
                'question_type' => 'single_choice',
                'options'       => json_encode(['完全符合', '大部分符合', '部分符合', '少部分符合', '不符合']),
                'weight'        => 0.10,
                'order'         => 3,
                'is_required'   => true,
                'sasb_topic_id' => null,
                'sasb_metric_code' => null,
                'tags'          => null,
                'source_bank_question_id' => null,
                'tag_slugs'     => ['esg.e.water'],
            ],
            [
                'template_id'   => null,
                'question_text' => '貴公司是否導入再生能源（如太陽能、購買 REC），並揭露再生能源佔總用電量的比例？',
                'question_type' => 'single_choice',
                'options'       => json_encode(['完全符合', '大部分符合', '部分符合', '少部分符合', '不符合']),
                'weight'        => 0.10,
                'order'         => 4,
                'is_required'   => true,
                'sasb_topic_id' => null,
                'sasb_metric_code' => null,
                'tags'          => null,
                'source_bank_question_id' => null,
                'tag_slugs'     => ['esg.e.energy'],
            ],
            [
                'template_id'   => null,
                'question_text' => '貴公司是否依據廢棄物分類要求進行廢棄物管理，並追蹤危險廢棄物的處置方式？',
                'question_type' => 'single_choice',
                'options'       => json_encode(['完全符合', '大部分符合', '部分符合', '少部分符合', '不符合']),
                'weight'        => 0.08,
                'order'         => 5,
                'is_required'   => true,
                'sasb_topic_id' => null,
                'sasb_metric_code' => null,
                'tags'          => null,
                'source_bank_question_id' => null,
                'tag_slugs'     => ['esg.e.waste'],
            ],
            [
                'template_id'   => null,
                'question_text' => '貴公司是否制定強迫勞動防制政策，並要求供應商簽署相關承諾書或行為準則？',
                'question_type' => 'single_choice',
                'options'       => json_encode(['完全符合', '大部分符合', '部分符合', '少部分符合', '不符合']),
                'weight'        => 0.12,
                'order'         => 6,
                'is_required'   => true,
                'sasb_topic_id' => null,
                'sasb_metric_code' => null,
                'tags'          => null,
                'source_bank_question_id' => null,
                'tag_slugs'     => ['esg.s.forced_labor'],
            ],
            [
                'template_id'   => null,
                'question_text' => '貴公司是否建立職業安全衛生管理系統（如 ISO 45001），並定期進行職災統計與預防訓練？',
                'question_type' => 'single_choice',
                'options'       => json_encode(['完全符合', '大部分符合', '部分符合', '少部分符合', '不符合']),
                'weight'        => 0.10,
                'order'         => 7,
                'is_required'   => true,
                'sasb_topic_id' => null,
                'sasb_metric_code' => null,
                'tags'          => null,
                'source_bank_question_id' => null,
                'tag_slugs'     => ['esg.s.ohs'],
            ],
            [
                'template_id'   => null,
                'question_text' => '貴公司董事會是否設有 ESG/永續委員會，並定期向董事會報告永續績效？',
                'question_type' => 'single_choice',
                'options'       => json_encode(['完全符合', '大部分符合', '部分符合', '少部分符合', '不符合']),
                'weight'        => 0.10,
                'order'         => 8,
                'is_required'   => true,
                'sasb_topic_id' => null,
                'sasb_metric_code' => null,
                'tags'          => null,
                'source_bank_question_id' => null,
                'tag_slugs'     => ['esg.g.board'],
            ],
            [
                'template_id'   => null,
                'question_text' => '貴公司是否建立反腐敗與反賄賂政策，並要求員工及供應商接受相關訓練？',
                'question_type' => 'single_choice',
                'options'       => json_encode(['完全符合', '大部分符合', '部分符合', '少部分符合', '不符合']),
                'weight'        => 0.08,
                'order'         => 9,
                'is_required'   => true,
                'sasb_topic_id' => null,
                'sasb_metric_code' => null,
                'tags'          => null,
                'source_bank_question_id' => null,
                'tag_slugs'     => ['esg.g.anti_corruption'],
            ],
            [
                'template_id'   => null,
                'question_text' => '貴公司是否揭露供應鏈的 Tier 1 供應商名單，並定期評估供應商 ESG 績效？',
                'question_type' => 'single_choice',
                'options'       => json_encode(['完全符合', '大部分符合', '部分符合', '少部分符合', '不符合']),
                'weight'        => 0.05,
                'order'         => 10,
                'is_required'   => false,
                'sasb_topic_id' => null,
                'sasb_metric_code' => null,
                'tags'          => null,
                'source_bank_question_id' => null,
                'tag_slugs'     => ['esg.g.supply_chain'],
            ],

            // ────────────────────────────────────────────────────────────
            // ISO20400 領域（10 題）
            // ────────────────────────────────────────────────────────────
            [
                'template_id'   => null,
                'question_text' => '貴公司是否制定符合 ISO 20400 精神的永續採購政策，並由高階管理層正式批准？',
                'question_type' => 'single_choice',
                'options'       => json_encode(['完全符合', '大部分符合', '部分符合', '少部分符合', '不符合']),
                'weight'        => 0.12,
                'order'         => 1,
                'is_required'   => true,
                'sasb_topic_id' => null,
                'sasb_metric_code' => null,
                'tags'          => null,
                'source_bank_question_id' => null,
                'tag_slugs'     => ['iso20400.org_gov.policy'],
            ],
            [
                'template_id'   => null,
                'question_text' => '貴公司是否對採購活動進行永續影響評估，並將評估結果納入供應商選擇決策？',
                'question_type' => 'single_choice',
                'options'       => json_encode(['完全符合', '大部分符合', '部分符合', '少部分符合', '不符合']),
                'weight'        => 0.10,
                'order'         => 2,
                'is_required'   => true,
                'sasb_topic_id' => null,
                'sasb_metric_code' => null,
                'tags'          => null,
                'source_bank_question_id' => null,
                'tag_slugs'     => ['iso20400.org_gov.audit'],
            ],
            [
                'template_id'   => null,
                'question_text' => '貴公司採購合約是否明確禁止強迫勞動、債務勞役及人口販運，並要求供應商自我聲明？',
                'question_type' => 'single_choice',
                'options'       => json_encode(['完全符合', '大部分符合', '部分符合', '少部分符合', '不符合']),
                'weight'        => 0.12,
                'order'         => 3,
                'is_required'   => true,
                'sasb_topic_id' => null,
                'sasb_metric_code' => null,
                'tags'          => json_encode([]),
                'source_bank_question_id' => null,
                'tag_slugs'     => ['iso20400.human_rights.forced_labor'],
            ],
            [
                'template_id'   => null,
                'question_text' => '貴公司是否尊重供應商員工的結社自由與集體談判權利，並在合約中明確約定？',
                'question_type' => 'single_choice',
                'options'       => json_encode(['完全符合', '大部分符合', '部分符合', '少部分符合', '不符合']),
                'weight'        => 0.08,
                'order'         => 4,
                'is_required'   => true,
                'sasb_topic_id' => null,
                'sasb_metric_code' => null,
                'tags'          => null,
                'source_bank_question_id' => null,
                'tag_slugs'     => ['iso20400.human_rights.freedom_of_association'],
            ],
            [
                'template_id'   => null,
                'question_text' => '貴公司是否確認供應商遵守當地法定最低工資及工時規定，並保留相關稽核紀錄？',
                'question_type' => 'single_choice',
                'options'       => json_encode(['完全符合', '大部分符合', '部分符合', '少部分符合', '不符合']),
                'weight'        => 0.10,
                'order'         => 5,
                'is_required'   => true,
                'sasb_topic_id' => null,
                'sasb_metric_code' => null,
                'tags'          => null,
                'source_bank_question_id' => null,
                'tag_slugs'     => ['iso20400.labor.wages_hours'],
            ],
            [
                'template_id'   => null,
                'question_text' => '貴公司是否要求供應商提供 ISO 45001 或同等職業安全衛生認證，或定期接受工廠安全稽核？',
                'question_type' => 'single_choice',
                'options'       => json_encode(['完全符合', '大部分符合', '部分符合', '少部分符合', '不符合']),
                'weight'        => 0.10,
                'order'         => 6,
                'is_required'   => true,
                'sasb_topic_id' => null,
                'sasb_metric_code' => null,
                'tags'          => null,
                'source_bank_question_id' => null,
                'tag_slugs'     => ['iso20400.labor.ohs'],
            ],
            [
                'template_id'   => null,
                'question_text' => '貴公司採購決策是否將供應商碳排放強度納入評估，並要求提供排放數據？',
                'question_type' => 'single_choice',
                'options'       => json_encode(['完全符合', '大部分符合', '部分符合', '少部分符合', '不符合']),
                'weight'        => 0.10,
                'order'         => 7,
                'is_required'   => true,
                'sasb_topic_id' => null,
                'sasb_metric_code' => null,
                'tags'          => null,
                'source_bank_question_id' => null,
                'tag_slugs'     => ['iso20400.environment.ghg'],
            ],
            [
                'template_id'   => null,
                'question_text' => '貴公司是否要求供應商提供廢棄物及危險化學品的管理計畫？',
                'question_type' => 'single_choice',
                'options'       => json_encode(['完全符合', '大部分符合', '部分符合', '少部分符合', '不符合']),
                'weight'        => 0.08,
                'order'         => 8,
                'is_required'   => false,
                'sasb_topic_id' => null,
                'sasb_metric_code' => null,
                'tags'          => null,
                'source_bank_question_id' => null,
                'tag_slugs'     => ['iso20400.environment.waste'],
            ],
            [
                'template_id'   => null,
                'question_text' => '貴公司是否在採購流程中推行反賄賂政策，並要求供應商簽署廉潔承諾書？',
                'question_type' => 'single_choice',
                'options'       => json_encode(['完全符合', '大部分符合', '部分符合', '少部分符合', '不符合']),
                'weight'        => 0.10,
                'order'         => 9,
                'is_required'   => true,
                'sasb_topic_id' => null,
                'sasb_metric_code' => null,
                'tags'          => null,
                'source_bank_question_id' => null,
                'tag_slugs'     => ['iso20400.fair_ops.anti_bribery'],
            ],
            [
                'template_id'   => null,
                'question_text' => '貴公司是否優先採購在地供應商，以支持地方經濟發展並降低運輸碳排放？',
                'question_type' => 'single_choice',
                'options'       => json_encode(['完全符合', '大部分符合', '部分符合', '少部分符合', '不符合']),
                'weight'        => 0.10,
                'order'         => 10,
                'is_required'   => false,
                'sasb_topic_id' => null,
                'sasb_metric_code' => null,
                'tags'          => null,
                'source_bank_question_id' => null,
                'tag_slugs'     => ['iso20400.community.local_procurement'],
            ],

            // ────────────────────────────────────────────────────────────
            // Geo-Risk 領域（10 題）
            // ────────────────────────────────────────────────────────────
            [
                'template_id'   => null,
                'question_text' => '貴公司是否對所有供應商進行制裁名單（OFAC、UN、EU）的定期篩查，並記錄篩查結果？',
                'question_type' => 'single_choice',
                'options'       => json_encode(['完全符合', '大部分符合', '部分符合', '少部分符合', '不符合']),
                'weight'        => 0.15,
                'order'         => 1,
                'is_required'   => true,
                'sasb_topic_id' => null,
                'sasb_metric_code' => null,
                'tags'          => null,
                'source_bank_question_id' => null,
                'tag_slugs'     => ['geo_risk.political.sanctions'],
            ],
            [
                'template_id'   => null,
                'question_text' => '貴公司是否評估主要供應商所在國家的政治穩定性及政策風險，並納入供應商評級？',
                'question_type' => 'single_choice',
                'options'       => json_encode(['完全符合', '大部分符合', '部分符合', '少部分符合', '不符合']),
                'weight'        => 0.12,
                'order'         => 2,
                'is_required'   => true,
                'sasb_topic_id' => null,
                'sasb_metric_code' => null,
                'tags'          => null,
                'source_bank_question_id' => null,
                'tag_slugs'     => ['geo_risk.political.risk'],
            ],
            [
                'template_id'   => null,
                'question_text' => '貴公司是否評估供應商所在地區的自然災害（地震、洪水、颱風）暴露程度，並建立應急備援計畫？',
                'question_type' => 'single_choice',
                'options'       => json_encode(['完全符合', '大部分符合', '部分符合', '少部分符合', '不符合']),
                'weight'        => 0.12,
                'order'         => 3,
                'is_required'   => true,
                'sasb_topic_id' => null,
                'sasb_metric_code' => null,
                'tags'          => null,
                'source_bank_question_id' => null,
                'tag_slugs'     => ['geo_risk.logistics.natural_disaster'],
            ],
            [
                'template_id'   => null,
                'question_text' => '貴公司是否建立供應鏈中斷風險管理機制（含備用供應商名單及庫存緩衝策略）？',
                'question_type' => 'single_choice',
                'options'       => json_encode(['完全符合', '大部分符合', '部分符合', '少部分符合', '不符合']),
                'weight'        => 0.12,
                'order'         => 4,
                'is_required'   => true,
                'sasb_topic_id' => null,
                'sasb_metric_code' => null,
                'tags'          => null,
                'source_bank_question_id' => null,
                'tag_slugs'     => ['geo_risk.logistics.disruption'],
            ],
            [
                'template_id'   => null,
                'question_text' => '貴公司在高風險地區的供應商是否接受現代奴役風險評估，包括招募費用及債務勞役調查？',
                'question_type' => 'single_choice',
                'options'       => json_encode(['完全符合', '大部分符合', '部分符合', '少部分符合', '不符合']),
                'weight'        => 0.12,
                'order'         => 5,
                'is_required'   => true,
                'sasb_topic_id' => null,
                'sasb_metric_code' => null,
                'tags'          => null,
                'source_bank_question_id' => null,
                'tag_slugs'     => ['geo_risk.labor.modern_slavery'],
            ],
            [
                'template_id'   => null,
                'question_text' => '貴公司是否要求高風險地區供應商提供童工防制相關政策及年齡查驗記錄？',
                'question_type' => 'single_choice',
                'options'       => json_encode(['完全符合', '大部分符合', '部分符合', '少部分符合', '不符合']),
                'weight'        => 0.10,
                'order'         => 6,
                'is_required'   => true,
                'sasb_topic_id' => null,
                'sasb_metric_code' => null,
                'tags'          => null,
                'source_bank_question_id' => null,
                'tag_slugs'     => ['geo_risk.labor.child_labor'],
            ],
            [
                'template_id'   => null,
                'question_text' => '貴公司主要採購地區中，有多少比例的供應商位於 Tier-1 制裁風險國家？',
                'question_type' => 'single_choice',
                'options'       => json_encode(['0%', '1–10%', '11–30%', '31–50%', '50% 以上']),
                'weight'        => 0.08,
                'order'         => 7,
                'is_required'   => false,
                'sasb_topic_id' => null,
                'sasb_metric_code' => null,
                'tags'          => null,
                'source_bank_question_id' => null,
                'tag_slugs'     => ['geo_risk.political.sanctions', 'geo_risk.political.risk'],
            ],
            [
                'template_id'   => null,
                'question_text' => '貴公司是否定期演練供應鏈中斷情境（如港口封鎖、重要原料短缺），並有演練紀錄？',
                'question_type' => 'boolean',
                'options'       => null,
                'weight'        => 0.07,
                'order'         => 8,
                'is_required'   => false,
                'sasb_topic_id' => null,
                'sasb_metric_code' => null,
                'tags'          => null,
                'source_bank_question_id' => null,
                'tag_slugs'     => ['geo_risk.logistics.disruption'],
            ],
            [
                'template_id'   => null,
                'question_text' => '貴公司是否訂閱地緣政治風險預警服務（如 MSCI ESG、Verisk Maplecroft），以即時監控供應商所在地區？',
                'question_type' => 'boolean',
                'options'       => null,
                'weight'        => 0.07,
                'order'         => 9,
                'is_required'   => false,
                'sasb_topic_id' => null,
                'sasb_metric_code' => null,
                'tags'          => null,
                'source_bank_question_id' => null,
                'tag_slugs'     => ['geo_risk.political.risk'],
            ],
            [
                'template_id'   => null,
                'question_text' => '貴公司是否在物流合約中納入不可抗力（Force Majeure）條款，並明確定義天災、戰爭、制裁的觸發情境？',
                'question_type' => 'boolean',
                'options'       => null,
                'weight'        => 0.05,
                'order'         => 10,
                'is_required'   => false,
                'sasb_topic_id' => null,
                'sasb_metric_code' => null,
                'tags'          => null,
                'source_bank_question_id' => null,
                'tag_slugs'     => ['geo_risk.logistics.disruption', 'geo_risk.political.risk'],
            ],

            // ────────────────────────────────────────────────────────────
            // Product-Compliance 領域（10 題）
            // ────────────────────────────────────────────────────────────
            [
                'template_id'   => null,
                'question_text' => '貴公司產品是否符合 RoHS 指令（2011/65/EU），並持有有效的 RoHS 合規聲明（DoC）？',
                'question_type' => 'single_choice',
                'options'       => json_encode(['完全符合', '大部分符合', '部分符合', '少部分符合', '不符合']),
                'weight'        => 0.15,
                'order'         => 1,
                'is_required'   => true,
                'sasb_topic_id' => null,
                'sasb_metric_code' => null,
                'tags'          => null,
                'source_bank_question_id' => null,
                'tag_slugs'     => ['product_compliance.chemical.rohs'],
            ],
            [
                'template_id'   => null,
                'question_text' => '貴公司使用的化學物質是否已依 REACH 法規完成 SVHC（高度關切物質）清單揭露，並通知客戶？',
                'question_type' => 'single_choice',
                'options'       => json_encode(['完全符合', '大部分符合', '部分符合', '少部分符合', '不符合']),
                'weight'        => 0.12,
                'order'         => 2,
                'is_required'   => true,
                'sasb_topic_id' => null,
                'sasb_metric_code' => null,
                'tags'          => null,
                'source_bank_question_id' => null,
                'tag_slugs'     => ['product_compliance.chemical.reach'],
            ],
            [
                'template_id'   => null,
                'question_text' => '貴公司是否完成衝突礦物盡職調查（CMRT），並能追溯錫、鉭、鎢、金（3TG）的來源至冶煉廠？',
                'question_type' => 'single_choice',
                'options'       => json_encode(['完全符合', '大部分符合', '部分符合', '少部分符合', '不符合']),
                'weight'        => 0.12,
                'order'         => 3,
                'is_required'   => true,
                'sasb_topic_id' => null,
                'sasb_metric_code' => null,
                'tags'          => null,
                'source_bank_question_id' => null,
                'tag_slugs'     => ['product_compliance.chemical.conflict_minerals'],
            ],
            [
                'template_id'   => null,
                'question_text' => '貴公司出口至歐盟的碳密集商品（鋼鐵、水泥、鋁等）是否已評估 CBAM 影響，並準備相關碳含量數據？',
                'question_type' => 'single_choice',
                'options'       => json_encode(['完全符合', '大部分符合', '部分符合', '少部分符合', '不符合']),
                'weight'        => 0.12,
                'order'         => 4,
                'is_required'   => true,
                'sasb_topic_id' => null,
                'sasb_metric_code' => null,
                'tags'          => null,
                'source_bank_question_id' => null,
                'tag_slugs'     => ['product_compliance.trade.cbam'],
            ],
            [
                'template_id'   => null,
                'question_text' => '貴公司是否建立出口管制審查程序（EAR/ITAR 或當地法規），確保敏感技術或商品不出口至受限終端用戶？',
                'question_type' => 'single_choice',
                'options'       => json_encode(['完全符合', '大部分符合', '部分符合', '少部分符合', '不符合']),
                'weight'        => 0.10,
                'order'         => 5,
                'is_required'   => true,
                'sasb_topic_id' => null,
                'sasb_metric_code' => null,
                'tags'          => null,
                'source_bank_question_id' => null,
                'tag_slugs'     => ['product_compliance.trade.export_control'],
            ],
            [
                'template_id'   => null,
                'question_text' => '貴公司是否了解並遵守主要出口市場的原產地規則（如 FTA 優惠關稅資格認定），並保留相關文件 5 年以上？',
                'question_type' => 'single_choice',
                'options'       => json_encode(['完全符合', '大部分符合', '部分符合', '少部分符合', '不符合']),
                'weight'        => 0.08,
                'order'         => 6,
                'is_required'   => false,
                'sasb_topic_id' => null,
                'sasb_metric_code' => null,
                'tags'          => null,
                'source_bank_question_id' => null,
                'tag_slugs'     => ['product_compliance.trade.rules_of_origin'],
            ],
            [
                'template_id'   => null,
                'question_text' => '貴公司產品是否取得目標市場所需之 CE 標誌（歐盟）或 UL 認證（美國），並在有效期內維護認證文件？',
                'question_type' => 'single_choice',
                'options'       => json_encode(['完全符合', '大部分符合', '部分符合', '少部分符合', '不符合']),
                'weight'        => 0.10,
                'order'         => 7,
                'is_required'   => true,
                'sasb_topic_id' => null,
                'sasb_metric_code' => null,
                'tags'          => null,
                'source_bank_question_id' => null,
                'tag_slugs'     => ['product_compliance.safety.certification'],
            ],
            [
                'template_id'   => null,
                'question_text' => '貴公司是否通過 ISO 9001 品質管理系統認證，並定期進行內部審核與管理審查？',
                'question_type' => 'single_choice',
                'options'       => json_encode(['完全符合', '大部分符合', '部分符合', '少部分符合', '不符合']),
                'weight'        => 0.08,
                'order'         => 8,
                'is_required'   => false,
                'sasb_topic_id' => null,
                'sasb_metric_code' => null,
                'tags'          => null,
                'source_bank_question_id' => null,
                'tag_slugs'     => ['product_compliance.safety.qms'],
            ],
            [
                'template_id'   => null,
                'question_text' => '貴公司產品是否符合目標市場的電磁相容性（EMC）標準，並持有有效測試報告？',
                'question_type' => 'boolean',
                'options'       => null,
                'weight'        => 0.07,
                'order'         => 9,
                'is_required'   => false,
                'sasb_topic_id' => null,
                'sasb_metric_code' => null,
                'tags'          => null,
                'source_bank_question_id' => null,
                'tag_slugs'     => ['product_compliance.safety.certification'],
            ],
            [
                'template_id'   => null,
                'question_text' => '貴公司是否建立化學品安全資料表（SDS）管理系統，確保所有使用化學品的 SDS 為最新版本且可即時取得？',
                'question_type' => 'boolean',
                'options'       => null,
                'weight'        => 0.06,
                'order'         => 10,
                'is_required'   => false,
                'sasb_topic_id' => null,
                'sasb_metric_code' => null,
                'tags'          => null,
                'source_bank_question_id' => null,
                'tag_slugs'     => ['product_compliance.chemical.reach', 'product_compliance.chemical.rohs'],
            ],

            // ────────────────────────────────────────────────────────────
            // 文字題（5 題）
            // ────────────────────────────────────────────────────────────
            [
                'template_id'   => null,
                'question_text' => '請簡述貴公司在過去一年內推動溫室氣體減量的具體措施，並說明達成的量化成效。',
                'question_type' => 'text',
                'options'       => null,
                'weight'        => 0.08,
                'order'         => 1,
                'is_required'   => true,
                'sasb_topic_id' => null,
                'sasb_metric_code' => null,
                'tags'          => null,
                'source_bank_question_id' => null,
                'scoring_type'  => 'llm',
                'tag_slugs'     => ['esg.e.ghg'],
            ],
            [
                'template_id'   => null,
                'question_text' => '請說明貴公司如何識別及管理供應鏈中的強迫勞動風險，包括盡職調查流程與矯正行動機制。',
                'question_type' => 'text',
                'options'       => null,
                'weight'        => 0.07,
                'order'         => 2,
                'is_required'   => true,
                'sasb_topic_id' => null,
                'sasb_metric_code' => null,
                'tags'          => null,
                'source_bank_question_id' => null,
                'scoring_type'  => 'llm',
                'tag_slugs'     => ['esg.s.forced_labor', 'iso20400.human_rights.forced_labor'],
            ],
            [
                'template_id'   => null,
                'question_text' => '貴公司水資源管理政策的核心內容為何？請列舉節水目標、監測方法及過去兩年的節水成效。',
                'question_type' => 'text',
                'options'       => null,
                'weight'        => 0.06,
                'order'         => 3,
                'is_required'   => false,
                'sasb_topic_id' => null,
                'sasb_metric_code' => null,
                'tags'          => null,
                'source_bank_question_id' => null,
                'scoring_type'  => 'llm',
                'tag_slugs'     => ['esg.e.water'],
            ],
            [
                'template_id'   => null,
                'question_text' => '請描述貴公司反腐敗與商業道德政策的主要內容，以及員工教育訓練與檢舉機制的實施方式。',
                'question_type' => 'text',
                'options'       => null,
                'weight'        => 0.06,
                'order'         => 4,
                'is_required'   => false,
                'sasb_topic_id' => null,
                'sasb_metric_code' => null,
                'tags'          => null,
                'source_bank_question_id' => null,
                'scoring_type'  => 'llm',
                'tag_slugs'     => ['esg.g.anti_corruption', 'iso20400.fair_ops.anti_bribery'],
            ],
            [
                'template_id'   => null,
                'question_text' => '若貴公司目前尚未取得任何 ESG 相關認證，請說明原因及未來 12 個月內的改善計畫。',
                'question_type' => 'text',
                'options'       => null,
                'weight'        => 0.05,
                'order'         => 5,
                'is_required'   => false,
                'sasb_topic_id' => null,
                'sasb_metric_code' => null,
                'tags'          => null,
                'source_bank_question_id' => null,
                'scoring_type'  => 'evidence_only',
                'tag_slugs'     => ['esg.g.compliance'],
            ],

            // ────────────────────────────────────────────────────────────
            // 多選題（5 題）
            // ────────────────────────────────────────────────────────────
            [
                'template_id'   => null,
                'question_text' => '貴公司目前已取得哪些國際永續相關認證？（可複選）',
                'question_type' => 'multiple_choice',
                'options'       => json_encode(['ISO 14001（環境管理）', 'ISO 45001（職安管理）', 'ISO 50001（能源管理）', 'SA8000（社會責任）', 'B Corp 認證', 'CDP 揭露', '目前尚未取得任何認證']),
                'weight'        => 0.08,
                'order'         => 1,
                'is_required'   => true,
                'sasb_topic_id' => null,
                'sasb_metric_code' => null,
                'tags'          => null,
                'source_bank_question_id' => null,
                'tag_slugs'     => ['esg.g.compliance', 'iso20400.org_gov.audit'],
            ],
            [
                'template_id'   => null,
                'question_text' => '貴公司在職場健康與安全方面，實施了哪些預防措施？（可複選）',
                'question_type' => 'multiple_choice',
                'options'       => json_encode(['定期安全教育訓練', '危害辨識與風險評估（HIRA）', '職安委員會運作', '事故調查與改善追蹤', '個人防護裝備管理制度', '健康促進方案（EAP）']),
                'weight'        => 0.07,
                'order'         => 2,
                'is_required'   => true,
                'sasb_topic_id' => null,
                'sasb_metric_code' => null,
                'tags'          => null,
                'source_bank_question_id' => null,
                'tag_slugs'     => ['esg.s.ohs', 'iso20400.labor.ohs'],
            ],
            [
                'template_id'   => null,
                'question_text' => '貴公司採用哪些再生能源或節能技術？（可複選）',
                'question_type' => 'multiple_choice',
                'options'       => json_encode(['太陽能發電（自建）', '採購再生能源憑證（REC）', 'LED 照明改善', '高效率空調系統', '廢熱回收系統', '智慧能源管理系統（BEMS/FEMS）', '目前尚未採用']),
                'weight'        => 0.07,
                'order'         => 3,
                'is_required'   => false,
                'sasb_topic_id' => null,
                'sasb_metric_code' => null,
                'tags'          => null,
                'source_bank_question_id' => null,
                'tag_slugs'     => ['esg.e.energy', 'iso20400.environment.ghg'],
            ],
            [
                'template_id'   => null,
                'question_text' => '貴公司在供應商管理上執行哪些盡職調查措施？（可複選）',
                'question_type' => 'multiple_choice',
                'options'       => json_encode(['ESG 自評問卷（SAQ）', '現場稽核', '第三方查核', '合約 ESG 條款', '制裁名單篩查', '碳排放資料收集', '目前未有系統性措施']),
                'weight'        => 0.08,
                'order'         => 4,
                'is_required'   => true,
                'sasb_topic_id' => null,
                'sasb_metric_code' => null,
                'tags'          => null,
                'source_bank_question_id' => null,
                'tag_slugs'     => ['esg.g.supply_chain', 'iso20400.org_gov.audit'],
            ],
            [
                'template_id'   => null,
                'question_text' => '貴公司廢棄物處理採用哪些方式？（可複選）',
                'question_type' => 'multiple_choice',
                'options'       => json_encode(['回收再利用', '能源回收（焚化發電）', '委託合法清除業者處理', '廢棄物減量製程改善', '危廢分類與安全儲存', '循環包裝設計']),
                'weight'        => 0.06,
                'order'         => 5,
                'is_required'   => false,
                'sasb_topic_id' => null,
                'sasb_metric_code' => null,
                'tags'          => null,
                'source_bank_question_id' => null,
                'tag_slugs'     => ['esg.e.waste', 'iso20400.environment.waste'],
            ],

            // ────────────────────────────────────────────────────────────
            // 數字題（5 題）
            // ────────────────────────────────────────────────────────────
            [
                'template_id'   => null,
                'question_text' => '請填寫貴公司最近完整會計年度的 Scope 1 直接溫室氣體排放量（單位：公噸 CO₂e）。',
                'question_type' => 'number',
                'options'       => null,
                'weight'        => 0.08,
                'order'         => 1,
                'is_required'   => true,
                'sasb_topic_id' => null,
                'sasb_metric_code' => null,
                'tags'          => null,
                'source_bank_question_id' => null,
                'scoring_type'  => 'evidence_only',
                'tag_slugs'     => ['esg.e.ghg', 'iso20400.environment.ghg'],
            ],
            [
                'template_id'   => null,
                'question_text' => '請填寫貴公司最近完整會計年度的總用電量（單位：度 kWh）。',
                'question_type' => 'number',
                'options'       => null,
                'weight'        => 0.07,
                'order'         => 2,
                'is_required'   => true,
                'sasb_topic_id' => null,
                'sasb_metric_code' => null,
                'tags'          => null,
                'source_bank_question_id' => null,
                'scoring_type'  => 'evidence_only',
                'tag_slugs'     => ['esg.e.energy'],
            ],
            [
                'template_id'   => null,
                'question_text' => '請填寫貴公司最近完整會計年度的總用水量（單位：立方公尺 m³）。',
                'question_type' => 'number',
                'options'       => null,
                'weight'        => 0.06,
                'order'         => 3,
                'is_required'   => false,
                'sasb_topic_id' => null,
                'sasb_metric_code' => null,
                'tags'          => null,
                'source_bank_question_id' => null,
                'scoring_type'  => 'evidence_only',
                'tag_slugs'     => ['esg.e.water'],
            ],
            [
                'template_id'   => null,
                'question_text' => '貴公司過去 12 個月內，職業災害失能傷害頻率（LTIFR，每百萬工時）為多少？',
                'question_type' => 'number',
                'options'       => null,
                'weight'        => 0.07,
                'order'         => 4,
                'is_required'   => true,
                'sasb_topic_id' => null,
                'sasb_metric_code' => null,
                'tags'          => null,
                'source_bank_question_id' => null,
                'scoring_type'  => 'evidence_only',
                'tag_slugs'     => ['esg.s.ohs', 'iso20400.labor.ohs'],
            ],
            [
                'template_id'   => null,
                'question_text' => '貴公司女性員工佔全體員工的比例為多少百分比（%）？',
                'question_type' => 'number',
                'options'       => null,
                'weight'        => 0.05,
                'order'         => 5,
                'is_required'   => false,
                'sasb_topic_id' => null,
                'sasb_metric_code' => null,
                'tags'          => null,
                'source_bank_question_id' => null,
                'scoring_type'  => 'evidence_only',
                'tag_slugs'     => ['esg.s.deib'],
            ],
        ];
    }
}
