export interface Country {
  code: string
  name: string
  name_en: string
}

export const COUNTRIES: Country[] = [
  // 亞太
  { code: 'TW', name: '台灣', name_en: 'Taiwan' },
  { code: 'CN', name: '中國', name_en: 'China' },
  { code: 'JP', name: '日本', name_en: 'Japan' },
  { code: 'KR', name: '韓國', name_en: 'South Korea' },
  { code: 'VN', name: '越南', name_en: 'Vietnam' },
  { code: 'TH', name: '泰國', name_en: 'Thailand' },
  { code: 'MY', name: '馬來西亞', name_en: 'Malaysia' },
  { code: 'SG', name: '新加坡', name_en: 'Singapore' },
  { code: 'ID', name: '印尼', name_en: 'Indonesia' },
  { code: 'IN', name: '印度', name_en: 'India' },
  { code: 'PH', name: '菲律賓', name_en: 'Philippines' },
  { code: 'BD', name: '孟加拉', name_en: 'Bangladesh' },
  { code: 'PK', name: '巴基斯坦', name_en: 'Pakistan' },
  { code: 'LK', name: '斯里蘭卡', name_en: 'Sri Lanka' },
  { code: 'MM', name: '緬甸', name_en: 'Myanmar' },
  { code: 'KH', name: '柬埔寨', name_en: 'Cambodia' },
  { code: 'LA', name: '寮國', name_en: 'Laos' },
  { code: 'NP', name: '尼泊爾', name_en: 'Nepal' },
  { code: 'HK', name: '香港', name_en: 'Hong Kong' },
  { code: 'MO', name: '澳門', name_en: 'Macao' },
  { code: 'MN', name: '蒙古', name_en: 'Mongolia' },
  { code: 'AU', name: '澳大利亞', name_en: 'Australia' },
  { code: 'NZ', name: '紐西蘭', name_en: 'New Zealand' },
  // 歐洲
  { code: 'DE', name: '德國', name_en: 'Germany' },
  { code: 'FR', name: '法國', name_en: 'France' },
  { code: 'GB', name: '英國', name_en: 'United Kingdom' },
  { code: 'IT', name: '義大利', name_en: 'Italy' },
  { code: 'ES', name: '西班牙', name_en: 'Spain' },
  { code: 'NL', name: '荷蘭', name_en: 'Netherlands' },
  { code: 'BE', name: '比利時', name_en: 'Belgium' },
  { code: 'SE', name: '瑞典', name_en: 'Sweden' },
  { code: 'NO', name: '挪威', name_en: 'Norway' },
  { code: 'DK', name: '丹麥', name_en: 'Denmark' },
  { code: 'FI', name: '芬蘭', name_en: 'Finland' },
  { code: 'CH', name: '瑞士', name_en: 'Switzerland' },
  { code: 'AT', name: '奧地利', name_en: 'Austria' },
  { code: 'PL', name: '波蘭', name_en: 'Poland' },
  { code: 'CZ', name: '捷克', name_en: 'Czech Republic' },
  { code: 'SK', name: '斯洛伐克', name_en: 'Slovakia' },
  { code: 'HU', name: '匈牙利', name_en: 'Hungary' },
  { code: 'RO', name: '羅馬尼亞', name_en: 'Romania' },
  { code: 'BG', name: '保加利亞', name_en: 'Bulgaria' },
  { code: 'HR', name: '克羅埃西亞', name_en: 'Croatia' },
  { code: 'SI', name: '斯洛維尼亞', name_en: 'Slovenia' },
  { code: 'RS', name: '塞爾維亞', name_en: 'Serbia' },
  { code: 'PT', name: '葡萄牙', name_en: 'Portugal' },
  { code: 'GR', name: '希臘', name_en: 'Greece' },
  { code: 'IE', name: '愛爾蘭', name_en: 'Ireland' },
  { code: 'LU', name: '盧森堡', name_en: 'Luxembourg' },
  { code: 'LT', name: '立陶宛', name_en: 'Lithuania' },
  { code: 'LV', name: '拉脫維亞', name_en: 'Latvia' },
  { code: 'EE', name: '愛沙尼亞', name_en: 'Estonia' },
  { code: 'UA', name: '烏克蘭', name_en: 'Ukraine' },
  { code: 'BY', name: '白俄羅斯', name_en: 'Belarus' },
  { code: 'RU', name: '俄羅斯', name_en: 'Russia' },
  { code: 'TR', name: '土耳其', name_en: 'Turkey' },
  { code: 'IS', name: '冰島', name_en: 'Iceland' },
  { code: 'MT', name: '馬爾他', name_en: 'Malta' },
  { code: 'CY', name: '賽普勒斯', name_en: 'Cyprus' },
  { code: 'AL', name: '阿爾巴尼亞', name_en: 'Albania' },
  { code: 'BA', name: '波赫', name_en: 'Bosnia and Herzegovina' },
  { code: 'MK', name: '北馬其頓', name_en: 'North Macedonia' },
  { code: 'ME', name: '蒙特內哥羅', name_en: 'Montenegro' },
  { code: 'MD', name: '摩爾多瓦', name_en: 'Moldova' },
  // 美洲
  { code: 'US', name: '美國', name_en: 'United States' },
  { code: 'CA', name: '加拿大', name_en: 'Canada' },
  { code: 'MX', name: '墨西哥', name_en: 'Mexico' },
  { code: 'BR', name: '巴西', name_en: 'Brazil' },
  { code: 'AR', name: '阿根廷', name_en: 'Argentina' },
  { code: 'CL', name: '智利', name_en: 'Chile' },
  { code: 'CO', name: '哥倫比亞', name_en: 'Colombia' },
  { code: 'PE', name: '秘魯', name_en: 'Peru' },
  { code: 'VE', name: '委內瑞拉', name_en: 'Venezuela' },
  { code: 'EC', name: '厄瓜多', name_en: 'Ecuador' },
  { code: 'BO', name: '玻利維亞', name_en: 'Bolivia' },
  { code: 'PY', name: '巴拉圭', name_en: 'Paraguay' },
  { code: 'UY', name: '烏拉圭', name_en: 'Uruguay' },
  { code: 'GT', name: '瓜地馬拉', name_en: 'Guatemala' },
  { code: 'CR', name: '哥斯大黎加', name_en: 'Costa Rica' },
  { code: 'PA', name: '巴拿馬', name_en: 'Panama' },
  { code: 'CU', name: '古巴', name_en: 'Cuba' },
  { code: 'DO', name: '多明尼加', name_en: 'Dominican Republic' },
  { code: 'HN', name: '宏都拉斯', name_en: 'Honduras' },
  { code: 'SV', name: '薩爾瓦多', name_en: 'El Salvador' },
  { code: 'NI', name: '尼加拉瓜', name_en: 'Nicaragua' },
  { code: 'JM', name: '牙買加', name_en: 'Jamaica' },
  { code: 'TT', name: '千里達及托巴哥', name_en: 'Trinidad and Tobago' },
  // 中東
  { code: 'SA', name: '沙烏地阿拉伯', name_en: 'Saudi Arabia' },
  { code: 'AE', name: '阿聯酋', name_en: 'United Arab Emirates' },
  { code: 'IL', name: '以色列', name_en: 'Israel' },
  { code: 'IR', name: '伊朗', name_en: 'Iran' },
  { code: 'IQ', name: '伊拉克', name_en: 'Iraq' },
  { code: 'QA', name: '卡達', name_en: 'Qatar' },
  { code: 'KW', name: '科威特', name_en: 'Kuwait' },
  { code: 'BH', name: '巴林', name_en: 'Bahrain' },
  { code: 'OM', name: '阿曼', name_en: 'Oman' },
  { code: 'JO', name: '約旦', name_en: 'Jordan' },
  { code: 'LB', name: '黎巴嫩', name_en: 'Lebanon' },
  { code: 'SY', name: '敘利亞', name_en: 'Syria' },
  { code: 'YE', name: '葉門', name_en: 'Yemen' },
  { code: 'PS', name: '巴勒斯坦', name_en: 'Palestine' },
  // 非洲
  { code: 'ZA', name: '南非', name_en: 'South Africa' },
  { code: 'NG', name: '奈及利亞', name_en: 'Nigeria' },
  { code: 'EG', name: '埃及', name_en: 'Egypt' },
  { code: 'ET', name: '衣索比亞', name_en: 'Ethiopia' },
  { code: 'KE', name: '肯亞', name_en: 'Kenya' },
  { code: 'GH', name: '迦納', name_en: 'Ghana' },
  { code: 'TZ', name: '坦尚尼亞', name_en: 'Tanzania' },
  { code: 'UG', name: '烏干達', name_en: 'Uganda' },
  { code: 'MA', name: '摩洛哥', name_en: 'Morocco' },
  { code: 'DZ', name: '阿爾及利亞', name_en: 'Algeria' },
  { code: 'TN', name: '突尼西亞', name_en: 'Tunisia' },
  { code: 'LY', name: '利比亞', name_en: 'Libya' },
  { code: 'SD', name: '蘇丹', name_en: 'Sudan' },
  { code: 'CM', name: '喀麥隆', name_en: 'Cameroon' },
  { code: 'CI', name: '象牙海岸', name_en: "Côte d'Ivoire" },
  { code: 'SN', name: '塞內加爾', name_en: 'Senegal' },
  { code: 'MZ', name: '莫三比克', name_en: 'Mozambique' },
  { code: 'ZW', name: '辛巴威', name_en: 'Zimbabwe' },
  { code: 'ZM', name: '尚比亞', name_en: 'Zambia' },
  { code: 'AO', name: '安哥拉', name_en: 'Angola' },
  { code: 'CD', name: '剛果（金）', name_en: 'DR Congo' },
  { code: 'MG', name: '馬達加斯加', name_en: 'Madagascar' },
  // 其他 ISO 3166-1 alpha-2（補足至 196）
  { code: 'AF', name: '阿富汗', name_en: 'Afghanistan' },
  { code: 'AM', name: '亞美尼亞', name_en: 'Armenia' },
  { code: 'AZ', name: '亞塞拜然', name_en: 'Azerbaijan' },
  { code: 'GE', name: '喬治亞', name_en: 'Georgia' },
  { code: 'KZ', name: '哈薩克', name_en: 'Kazakhstan' },
  { code: 'KG', name: '吉爾吉斯', name_en: 'Kyrgyzstan' },
  { code: 'TJ', name: '塔吉克', name_en: 'Tajikistan' },
  { code: 'TM', name: '土庫曼', name_en: 'Turkmenistan' },
  { code: 'UZ', name: '烏茲別克', name_en: 'Uzbekistan' },
  { code: 'BT', name: '不丹', name_en: 'Bhutan' },
  { code: 'MV', name: '馬爾地夫', name_en: 'Maldives' },
  { code: 'BN', name: '汶萊', name_en: 'Brunei' },
  { code: 'TL', name: '東帝汶', name_en: 'Timor-Leste' },
  { code: 'FJ', name: '斐濟', name_en: 'Fiji' },
  { code: 'PG', name: '巴布亞紐幾內亞', name_en: 'Papua New Guinea' },
  { code: 'SB', name: '索羅門群島', name_en: 'Solomon Islands' },
  { code: 'VU', name: '萬那杜', name_en: 'Vanuatu' },
  { code: 'WS', name: '薩摩亞', name_en: 'Samoa' },
  { code: 'TO', name: '東加', name_en: 'Tonga' },
  { code: 'KI', name: '吉里巴斯', name_en: 'Kiribati' },
  { code: 'FM', name: '密克羅尼西亞', name_en: 'Micronesia' },
  { code: 'PW', name: '帛琉', name_en: 'Palau' },
  { code: 'MH', name: '馬紹爾群島', name_en: 'Marshall Islands' },
  { code: 'NR', name: '諾魯', name_en: 'Nauru' },
  { code: 'TV', name: '吐瓦魯', name_en: 'Tuvalu' },
  { code: 'CG', name: '剛果（布）', name_en: 'Republic of the Congo' },
  { code: 'CF', name: '中非', name_en: 'Central African Republic' },
  { code: 'TD', name: '查德', name_en: 'Chad' },
  { code: 'NE', name: '尼日', name_en: 'Niger' },
  { code: 'ML', name: '馬利', name_en: 'Mali' },
  { code: 'BF', name: '布吉納法索', name_en: 'Burkina Faso' },
  { code: 'GN', name: '幾內亞', name_en: 'Guinea' },
  { code: 'GW', name: '幾內亞比索', name_en: 'Guinea-Bissau' },
  { code: 'GM', name: '甘比亞', name_en: 'Gambia' },
  { code: 'SL', name: '獅子山', name_en: 'Sierra Leone' },
  { code: 'LR', name: '賴比瑞亞', name_en: 'Liberia' },
  { code: 'MR', name: '茅利塔尼亞', name_en: 'Mauritania' },
  { code: 'BI', name: '蒲隆地', name_en: 'Burundi' },
  { code: 'RW', name: '盧安達', name_en: 'Rwanda' },
  { code: 'BJ', name: '貝南', name_en: 'Benin' },
  { code: 'TG', name: '多哥', name_en: 'Togo' },
  { code: 'GA', name: '加彭', name_en: 'Gabon' },
  { code: 'GQ', name: '赤道幾內亞', name_en: 'Equatorial Guinea' },
  { code: 'ST', name: '聖多美普林西比', name_en: 'São Tomé and Príncipe' },
  { code: 'CV', name: '維德角', name_en: 'Cape Verde' },
  { code: 'KM', name: '葛摩', name_en: 'Comoros' },
  { code: 'SC', name: '塞席爾', name_en: 'Seychelles' },
  { code: 'MU', name: '模里西斯', name_en: 'Mauritius' },
  { code: 'ER', name: '厄利垂亞', name_en: 'Eritrea' },
  { code: 'DJ', name: '吉布地', name_en: 'Djibouti' },
  { code: 'SO', name: '索馬利亞', name_en: 'Somalia' },
  { code: 'SS', name: '南蘇丹', name_en: 'South Sudan' },
  { code: 'MW', name: '馬拉威', name_en: 'Malawi' },
  { code: 'NA', name: '納米比亞', name_en: 'Namibia' },
  { code: 'BW', name: '波札那', name_en: 'Botswana' },
  { code: 'LS', name: '賴索托', name_en: 'Lesotho' },
  { code: 'SZ', name: '史瓦帝尼', name_en: 'Eswatini' },
  { code: 'GY', name: '蓋亞那', name_en: 'Guyana' },
  { code: 'SR', name: '蘇利南', name_en: 'Suriname' },
  { code: 'BZ', name: '貝里斯', name_en: 'Belize' },
  { code: 'HT', name: '海地', name_en: 'Haiti' },
  { code: 'BB', name: '巴貝多', name_en: 'Barbados' },
  { code: 'AG', name: '安地卡及巴布達', name_en: 'Antigua and Barbuda' },
  { code: 'DM', name: '多米尼克', name_en: 'Dominica' },
  { code: 'GD', name: '格瑞那達', name_en: 'Grenada' },
  { code: 'KN', name: '聖克里斯多福及尼維斯', name_en: 'Saint Kitts and Nevis' },
  { code: 'LC', name: '聖露西亞', name_en: 'Saint Lucia' },
  { code: 'VC', name: '聖文森及格瑞那丁', name_en: 'Saint Vincent and the Grenadines' },
  { code: 'BS', name: '巴哈馬', name_en: 'Bahamas' },
  { code: 'TC', name: '土克凱科斯群島', name_en: 'Turks and Caicos Islands' },
  { code: 'KP', name: '北韓', name_en: 'North Korea' },
  { code: 'CX', name: '聖誕島', name_en: 'Christmas Island' },
  { code: 'LI', name: '列支敦斯登', name_en: 'Liechtenstein' },
  { code: 'MC', name: '摩納哥', name_en: 'Monaco' },
  { code: 'SM', name: '聖馬利諾', name_en: 'San Marino' },
  { code: 'VA', name: '梵蒂岡', name_en: 'Vatican City' },
  { code: 'AD', name: '安道爾', name_en: 'Andorra' },
  { code: 'MQ', name: '馬丁尼克', name_en: 'Martinique' },
  { code: 'GP', name: '瓜地洛普', name_en: 'Guadeloupe' },
  { code: 'RE', name: '留尼旺', name_en: 'Réunion' },
  { code: 'YT', name: '馬約特', name_en: 'Mayotte' },
  { code: 'PM', name: '聖皮埃爾和密克隆群島', name_en: 'Saint Pierre and Miquelon' },
  { code: 'GF', name: '法屬圭亞那', name_en: 'French Guiana' },
  { code: 'PF', name: '法屬玻里尼西亞', name_en: 'French Polynesia' },
  { code: 'NC', name: '新喀里多尼亞', name_en: 'New Caledonia' },
]

export function findCountry(code: string): Country | undefined {
  return COUNTRIES.find(c => c.code === code.toUpperCase())
}

export function countryDisplay(code: string | null | undefined): string {
  if (!code) return ''
  const c = findCountry(code)
  return c ? `${c.name} (${c.code})` : code
}
